export const AUTH_GOOGLE_REQUEST = 'auth/AUTH_GOOGLE_REQUEST';
export const AUTH_GOOGLE_SUCCESS = 'auth/AUTH_GOOGLE_SUCCESS';
export const AUTH_GOOGLE_ERROR = 'auth/AUTH_GOOGLE_ERROR';
export const AUTH_GOOGLE_LOGOUT = 'auth/AUTH_GOOGLE_LOGOUT';
export const AUTH_GOOGLE_CANCEL = 'auth/AUTH_GOOGLE_CANCEL';
export const AUTH_GOOGLE_FETCH_MESSAGE = 'auth/AUTH_GOOGLE_FETCH_MESSAGE';
